---
title: "load_prodes"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/README-",
  out.width = "100%")
```

Loads information on clearcut deforestation in the Legal Amazon and annual deforestation rates in the region. Survey is done at state or municipality level and data is available from 2000 to 2020.

# Usage:

```{r, eval = FALSE}
There are five parameters in this function:
  
  1. dataset = "prodes"

  2.raw_data : there are two options:
  
  # TRUE: if you want to visualize the raw data.
  # FALSE: if you want to visualize the processed version of the data. 
    
  3. geo_level: there are two options:
  
  # "state"
  # "municipality"
  
  4. time_period : available from 2000 to 2020

  5. language : you can choose between portuguese and english
  
  # "pt"
  # "eng"
```

# Examples:

```{r, eval = FALSE}
# Download raw data (raw_data = TRUE) by municipality (geo_level = "municipality") from 2000 to 2005 (time_period = 2000:2005) in english.

data = load_prodes(dataset = "prodes", raw_data = TRUE,
                        geo_level = "municipality", time_period = 2000:2005,
                        language = 'eng') 

# Download treated data (raw_data = FALSE) by state (geo_level = "state") from 2010 (time_period = 2010) in portuguese (language = 'pt').

data = load_prodes(dataset = "prodes", raw_data = FALSE,
                        geo_level = "state", time_period = 2010,
                        language = 'pt') 

````
